

corvus_main:
    path:     /
    defaults: { _controller: CorvusMainBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: CorvusMainBundle:Default:welcome }
    methods:  [GET, POST]

dashboard:
     path:     /dashboard
     defaults: { _controller: CorvusMainBundle:Default:dashboard }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

