food:
    resource: "@FoodBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /

corvus_main:
    resource: "@CorvusMainBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path:     /login
    defaults: { _controller: CorvusMainBundle:Default:welcome }
    methods:  [GET, POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"