parameters:

services:
    corvus_event.event_status:
        class: Corvus\EventBundle\EventListener\EventAltered
        tags:
          - {name: kernel.event_subscriber}

    corvus_event.send_mails:
        class: Corvus\EventBundle\EventListener\SendMails
        arguments:
          - @swiftmailer.mailer
          - @twig
        tags:
          - {name: kernel.event_subscriber}